// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhlhvoburvwjwdbqwzct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhobGh2b2J1cnZ3andkYnF3emN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjEzOTQsImV4cCI6MjA2NTE5NzM5NH0.nPKgow__pFsN733YAyx7YrCaP8hVcU3N1C-KFwwiYUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);